---
- hosts: all
  gather_facts: yes
  become: true
  vars:
    ansible_ssh_user: "{{ zuser }}" 
    ansible_ssh_pass: "{{ zpass }}"
    ansible_become_pass: "{{ zpass }}"

    ans_rol_k3s:
      dashboard: true
      helm: true
      namespace: true
      service_account: true
      service_account_names:
        - itadmin
        - jenkins

  roles:
    - name: K3S service
      role: ans-rol-k3s
